-- MySQL Script generated by MySQL Workbench
-- 10/15/14 15:13:45
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema contracts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contracts` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `contracts` ;

-- -----------------------------------------------------
-- Table `dict_orgforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dict_orgforms` (
  `ORGFORM_ID` INT(11) NOT NULL,
  `NAME` VARCHAR(10) NOT NULL,
  `FULL_NAME` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`ORGFORM_ID`),
  UNIQUE INDEX `ORGFORM_ID` (`ORGFORM_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companies` (
  `COMPANY_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(256) NOT NULL,
  `SHORT_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `ORGFORM_ID` INT(11) NOT NULL,
  PRIMARY KEY (`COMPANY_ID`),
  UNIQUE INDEX `COMPANY_ID` (`COMPANY_ID` ASC),
  INDEX `FK_COMPANY_ORGFORM` (`ORGFORM_ID` ASC),
  CONSTRAINT `FK_COMPANY_ORGFORM`
    FOREIGN KEY (`ORGFORM_ID`)
    REFERENCES `dict_orgforms` (`ORGFORM_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contracts` (
  `CONTRACT_ID` INT NOT NULL AUTO_INCREMENT,
  `CONTRACT_NUMBER` VARCHAR(64) NOT NULL COMMENT 'Основной номер договора',
  `CONTRACT_DATE` DATE NULL COMMENT 'Дата договора',
  `CUSTOMER_ID` INT NULL COMMENT 'ID компании-заказчика',
  `CUSTOMER_NUMBER` VARCHAR(64) NULL COMMENT 'Номер договора компании-заказчика',
  `CONTRACTOR_ID` INT NULL COMMENT 'ID компании-исполнителя',
  `CONTRACTOR_NUMBER` VARCHAR(64) NULL COMMENT 'Номер договора компании-исполнителя',
  `MAIN_NUMBER_FLAG` TINYINT(4) NULL COMMENT 'Пометка, чей номер договора - основной: 0 - исполнителя, 1 - заказчика',
  PRIMARY KEY (`CONTRACT_ID`),
  UNIQUE INDEX `CONTRACT_NUMBER_UNIQUE` (`CONTRACT_NUMBER` ASC),
  INDEX `FK_CONTRACT_CUSTOMER_idx` (`CUSTOMER_ID` ASC),
  INDEX `FK_CONTRACT_CONTRACTOR_idx` (`CONTRACTOR_ID` ASC),
  CONSTRAINT `FK_CONTRACT_CUSTOMER`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `companies` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CONTRACT_CONTRACTOR`
    FOREIGN KEY (`CONTRACTOR_ID`)
    REFERENCES `companies` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
