package com.example.contracts.ui.vaadin6;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NameClassPair;
import javax.naming.NamingEnumeration;
import javax.naming.NamingException;
import javax.sql.DataSource;

import org.springframework.context.ApplicationContext;

import com.example.contracts.services.CompanyService;
import com.example.contracts.utils.SpringUtil;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class MainWindowContainer extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    private static final long serialVersionUID = -2947084404659980577L;

    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private Panel mainWorkPanel;
    @AutoGenerated
    private VerticalLayout verticalLayout_1;
    @AutoGenerated
    private Label label_1;
    @AutoGenerated
    private MenuBar mainMenuBar;

    /**
     * The constructor should first build the main layout, set the composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the visual editor.
     */
    public MainWindowContainer() {
	buildMainLayout();
	setCompositionRoot(mainLayout);

	// TODO add user code here
	mainMenuBar.addItem("Компании", new Command() {
	    private static final long serialVersionUID = 1L;

	    @Override
	    public void menuSelected(MenuItem selectedItem) {
		mainWorkPanel.setContent(CompanyListView.getCompanyListView());
	    }

	});
	MenuItem itemLogout = mainMenuBar.addItem("Сгенерировать", new Command() {
	    private static final long serialVersionUID = 1L;

	    @Override
	    public void menuSelected(MenuItem selectedItem) {
		//generateCompanies();
		ApplicationContext ac = SpringUtil.getApplicationContext();
		CompanyService service = ac.getBean(CompanyService.class);
		service.generateCompanies();

		Context initCtx;
		try {
		    initCtx = new InitialContext();
		    Context envCtx = (Context) initCtx.lookup("java:comp/env");
		    System.out.println("envCtx=" + envCtx.composeName("", ""));
		    NamingEnumeration<NameClassPair> ctxs = envCtx.list("");
		    if (ctxs.hasMoreElements()) {
			NameClassPair pair = ctxs.nextElement();
			System.out.println("  " + pair.getName() + "=" + pair.getClassName());
		    }
		    DataSource ds = (DataSource) envCtx.lookup("jdbc/ContractsDB");

		    Connection conn = ds.getConnection();
		    PreparedStatement st = conn.prepareStatement("select count(*) from dict_orgforms");
		    ResultSet rs = st.executeQuery();
		    rs.next();
		    System.out.println("dict_orgforms row count=" + rs.getInt(1));
		    conn.close();
		} catch (NamingException e) {
		    // TODO Auto-generated catch block
		    e.printStackTrace();
		} catch (SQLException e) {
		    // TODO Auto-generated catch block
		    e.printStackTrace();
		}

	    }

	});
	itemLogout.addSeparatorBefore(itemLogout);

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
	// common part: create layout
	mainLayout = new VerticalLayout();
	mainLayout.setImmediate(false);
	mainLayout.setWidth("100%");
	mainLayout.setHeight("100%");
	mainLayout.setMargin(false);

	// top-level component properties
	setWidth("100.0%");
	setHeight("100.0%");

	// mainMenuBar
	mainMenuBar = new MenuBar();
	mainMenuBar.setImmediate(false);
	mainMenuBar.setWidth("100.0%");
	mainMenuBar.setHeight("-1px");
	mainLayout.addComponent(mainMenuBar);

	// mainWorkPanel
	mainWorkPanel = buildMainWorkPanel();
	mainLayout.addComponent(mainWorkPanel);
	mainLayout.setExpandRatio(mainWorkPanel, 1.0f);

	return mainLayout;
    }

    @AutoGenerated
    private Panel buildMainWorkPanel() {
	// common part: create layout
	mainWorkPanel = new Panel();
	mainWorkPanel.setImmediate(false);
	mainWorkPanel.setWidth("100.0%");
	mainWorkPanel.setHeight("100.0%");

	// verticalLayout_1
	verticalLayout_1 = buildVerticalLayout_1();
	mainWorkPanel.setContent(verticalLayout_1);

	return mainWorkPanel;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_1() {
	// common part: create layout
	verticalLayout_1 = new VerticalLayout();
	verticalLayout_1.setImmediate(false);
	verticalLayout_1.setWidth("100.0%");
	verticalLayout_1.setHeight("100.0%");
	verticalLayout_1.setMargin(true);

	// label_1
	label_1 = new Label();
	label_1.setImmediate(false);
	label_1.setWidth("150px");
	label_1.setHeight("-1px");
	label_1.setValue("Доброго времени суток!");
	verticalLayout_1.addComponent(label_1);
	verticalLayout_1.setComponentAlignment(label_1, new Alignment(48));

	return verticalLayout_1;
    }

}
